/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bookshelf.glb -o src/components/Bookshelf.tsx -r public -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    group1157935093: THREE.Mesh
    group1627220740: THREE.Mesh
    group1141386355: THREE.Mesh
    group570676340: THREE.Mesh
    group1232064123: THREE.Mesh
    group1653331851: THREE.Mesh
    group769714903: THREE.Mesh
    group1142439874: THREE.Mesh
    group358796304: THREE.Mesh
    group1530060255: THREE.Mesh
    group1017857667: THREE.Mesh
    group1910303946: THREE.Mesh
    group507504657: THREE.Mesh
    group417346667: THREE.Mesh
    group1151011112: THREE.Mesh
    group613892827: THREE.Mesh
    group49830189: THREE.Mesh
    group1663195276: THREE.Mesh
    group1436329055: THREE.Mesh
    group1809556686: THREE.Mesh
    group617875879: THREE.Mesh
    group291491869: THREE.Mesh
    group107655788: THREE.Mesh
    group947526354: THREE.Mesh
    group329433738: THREE.Mesh
    group861886169: THREE.Mesh
    group831925795: THREE.Mesh
    group381582310: THREE.Mesh
    group998673862: THREE.Mesh
    group1318288051: THREE.Mesh
    group317458115: THREE.Mesh
    group540085485: THREE.Mesh
    group1367506331: THREE.Mesh
    group69207291: THREE.Mesh
    group1594667082: THREE.Mesh
    group1473881261: THREE.Mesh
    group370831279: THREE.Mesh
    group1224876797: THREE.Mesh
    group731911737: THREE.Mesh
    group1653838410: THREE.Mesh
    group861266369: THREE.Mesh
    group1158707824: THREE.Mesh
    group67051637: THREE.Mesh
    group1064000530: THREE.Mesh
    group546095868: THREE.Mesh
    group157055117: THREE.Mesh
    group1923291102: THREE.Mesh
    group1481496857: THREE.Mesh
    group667857111: THREE.Mesh
    group813238547: THREE.Mesh
    group452256788: THREE.Mesh
    group602354389: THREE.Mesh
    group1138773620: THREE.Mesh
    group1460852964: THREE.Mesh
    group1570674232: THREE.Mesh
    group436422685: THREE.Mesh
    group136673378: THREE.Mesh
    group1339953517: THREE.Mesh
    group1062177206: THREE.Mesh
    group1775573242: THREE.Mesh
    group242614963: THREE.Mesh
    group1047440592: THREE.Mesh
    group546841190: THREE.Mesh
    group87010582: THREE.Mesh
    group1117099408: THREE.Mesh
    group2040258719: THREE.Mesh
    group1890477119: THREE.Mesh
    group1952238106: THREE.Mesh
    group874637944: THREE.Mesh
    group1849082664: THREE.Mesh
    group48647622: THREE.Mesh
    group1169737948: THREE.Mesh
    group1634753507: THREE.Mesh
    group698001646: THREE.Mesh
    group1518556478: THREE.Mesh
    group958391725: THREE.Mesh
    group562251177: THREE.Mesh
    group1181614673: THREE.Mesh
    group1124988245: THREE.Mesh
    group1625391926: THREE.Mesh
    group1739416736: THREE.Mesh
    group1974075975: THREE.Mesh
    group839136665: THREE.Mesh
    group1910844938: THREE.Mesh
    group1056511910: THREE.Mesh
    group284069880: THREE.Mesh
    group365452620: THREE.Mesh
    group732152197: THREE.Mesh
    group1080066371: THREE.Mesh
    group495478490: THREE.Mesh
    group1644687961: THREE.Mesh
    group835064279: THREE.Mesh
    group255968075: THREE.Mesh
    group2039374853: THREE.Mesh
    group404734624: THREE.Mesh
    group523105132: THREE.Mesh
    group105605934: THREE.Mesh
    group1779107521: THREE.Mesh
    group1023447742: THREE.Mesh
    group1656866261: THREE.Mesh
    group2000336328: THREE.Mesh
    group1232176128: THREE.Mesh
    group223040541: THREE.Mesh
    group2012211951: THREE.Mesh
    group1333586700: THREE.Mesh
    group763370712: THREE.Mesh
    group181388570: THREE.Mesh
    group1502342032: THREE.Mesh
    group37033037: THREE.Mesh
    group1544780229: THREE.Mesh
    group245789158: THREE.Mesh
    group1117173827: THREE.Mesh
    group618669869: THREE.Mesh
    group1957191458: THREE.Mesh
    group2074597356: THREE.Mesh
    group1090408012: THREE.Mesh
    group1703454340: THREE.Mesh
    group417023748: THREE.Mesh
    group1842469405: THREE.Mesh
    group510307397: THREE.Mesh
    group1298644762: THREE.Mesh
    group2031779489: THREE.Mesh
    group2082427630: THREE.Mesh
    group1052868563: THREE.Mesh
    group1328761992: THREE.Mesh
    group2040295764: THREE.Mesh
    group1402351385: THREE.Mesh
    group1874688432: THREE.Mesh
    group640489275: THREE.Mesh
    group1931339425: THREE.Mesh
    group745651501: THREE.Mesh
    group928962312: THREE.Mesh
    group70744352: THREE.Mesh
    group1441840083: THREE.Mesh
    group1665055780: THREE.Mesh
    group2086821730: THREE.Mesh
    group1812883658: THREE.Mesh
    group555744809: THREE.Mesh
    group805038488: THREE.Mesh
    group2137142006: THREE.Mesh
    group939507797: THREE.Mesh
    group1227664213: THREE.Mesh
    group588161149: THREE.Mesh
    group1200221018: THREE.Mesh
    group450345529: THREE.Mesh
    group1581940073: THREE.Mesh
    group1869578372: THREE.Mesh
    group1819635746: THREE.Mesh
    group993771361: THREE.Mesh
    group1239591964: THREE.Mesh
    group911214760: THREE.Mesh
    group1071374016: THREE.Mesh
    group1161431776: THREE.Mesh
    group928684105: THREE.Mesh
  }
  materials: {
    mat20: THREE.MeshStandardMaterial
    mat14: THREE.MeshStandardMaterial
    mat21: THREE.MeshStandardMaterial
    mat10: THREE.MeshStandardMaterial
    mat4: THREE.MeshStandardMaterial
    mat13: THREE.MeshStandardMaterial
    mat7: THREE.MeshStandardMaterial
    mat16: THREE.MeshStandardMaterial
    mat23: THREE.MeshStandardMaterial
    mat12: THREE.MeshStandardMaterial
    mat2: THREE.MeshStandardMaterial
    mat0: THREE.MeshStandardMaterial
    mat11: THREE.MeshStandardMaterial
    mat15: THREE.MeshStandardMaterial
    mat19: THREE.MeshStandardMaterial
    mat3: THREE.MeshStandardMaterial
    mat5: THREE.MeshStandardMaterial
    mat18: THREE.MeshStandardMaterial
    mat9: THREE.MeshStandardMaterial
    mat1: THREE.MeshStandardMaterial
    mat6: THREE.MeshStandardMaterial
    mat17: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export default function Bookshelf(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/bookshelf.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1157935093.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1627220740.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1141386355.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group570676340.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1232064123.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1653331851.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group769714903.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1142439874.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group358796304.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1530060255.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1017857667.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1910303946.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group507504657.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group417346667.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1151011112.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group613892827.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group49830189.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group1663195276.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1436329055.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1809556686.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group617875879.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group291491869.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group107655788.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group947526354.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group329433738.geometry} material={materials.mat7} />
      <mesh geometry={nodes.group861886169.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group831925795.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group381582310.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group998673862.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1318288051.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group317458115.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group540085485.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1367506331.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group69207291.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1594667082.geometry} material={materials.mat12} />
      <mesh geometry={nodes.group1473881261.geometry} material={materials.mat12} />
      <mesh geometry={nodes.group370831279.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1224876797.geometry} material={materials.mat12} />
      <mesh geometry={nodes.group731911737.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1653838410.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group861266369.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1158707824.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group67051637.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1064000530.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group546095868.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group157055117.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1923291102.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group1481496857.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group667857111.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group813238547.geometry} material={materials.mat4} />
      <mesh geometry={nodes.group452256788.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group602354389.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1138773620.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group1460852964.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group1570674232.geometry} material={materials.mat0} />
      <mesh geometry={nodes.group436422685.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group136673378.geometry} material={materials.mat0} />
      <mesh geometry={nodes.group1339953517.geometry} material={materials.mat0} />
      <mesh geometry={nodes.group1062177206.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1775573242.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group242614963.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1047440592.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group546841190.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group87010582.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group1117099408.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group2040258719.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1890477119.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1952238106.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group874637944.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1849082664.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group48647622.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1169737948.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1634753507.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group698001646.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1518556478.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group958391725.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group562251177.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1181614673.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group1124988245.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1625391926.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1739416736.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1974075975.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group839136665.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1910844938.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1056511910.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group284069880.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group365452620.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group732152197.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1080066371.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group495478490.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1644687961.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group835064279.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group255968075.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group2039374853.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group404734624.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group523105132.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group105605934.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1779107521.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1023447742.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1656866261.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group2000336328.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group1232176128.geometry} material={materials.mat14} />
      <mesh geometry={nodes.group223040541.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group2012211951.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1333586700.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group763370712.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group181388570.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group1502342032.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group37033037.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1544780229.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group245789158.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1117173827.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group618669869.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1957191458.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group2074597356.geometry} material={materials.mat1} />
      <mesh geometry={nodes.group1090408012.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1703454340.geometry} material={materials.mat1} />
      <mesh geometry={nodes.group417023748.geometry} material={materials.mat1} />
      <mesh geometry={nodes.group1842469405.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group510307397.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1298644762.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group2031779489.geometry} material={materials.mat11} />
      <mesh geometry={nodes.group2082427630.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1052868563.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1328761992.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group2040295764.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1402351385.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1874688432.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group640489275.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1931339425.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group745651501.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group928962312.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group70744352.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1441840083.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1665055780.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group2086821730.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1812883658.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group555744809.geometry} material={materials.mat6} />
      <mesh geometry={nodes.group805038488.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group2137142006.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group939507797.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group1227664213.geometry} material={materials.mat19} />
      <mesh geometry={nodes.group588161149.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1200221018.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group450345529.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1581940073.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1869578372.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group1819635746.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group993771361.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group1239591964.geometry} material={materials.mat2} />
      <mesh geometry={nodes.group911214760.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1071374016.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1161431776.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group928684105.geometry} material={materials.mat21} />
    </group>
  )
}

useGLTF.preload('/models/bookshelf.glb')
