/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chair.glb -o src/components/Chair.tsx -r public -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    ['Node-Mesh']: THREE.Mesh
    ['Node-Mesh_1']: THREE.Mesh
    ['Node-Mesh_2']: THREE.Mesh
  }
  materials: {
    Office_Cha: THREE.MeshStandardMaterial
    Office_Cha_1: THREE.MeshStandardMaterial
    Office_Cha_2: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export default function Chair(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/chair.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.Office_Cha} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.Office_Cha_1} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.Office_Cha_2} />
    </group>
  )
}

useGLTF.preload('/models/chair.glb')
