/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Frame.glb -o src/components/frame.tsx -r public -t 
*/

import * as THREE from "three"
import { useGLTF } from "@react-three/drei"
import type { GLTF } from "three-stdlib"
import type { JSX } from "react"

type GLTFResult = GLTF & {
	nodes: {
		group2129464214: THREE.Mesh
		group331407839: THREE.Mesh
		group1232702741: THREE.Mesh
		group825219810: THREE.Mesh
	}
	materials: {
		mat23: THREE.MeshStandardMaterial
	}
}

export default function Frame(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"/models/frame.glb"
	) as unknown as GLTFResult
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.group2129464214.geometry}
				material={materials.mat23}
			/>
			<mesh
				geometry={nodes.group331407839.geometry}
				material={materials.mat23}
			/>
			<mesh
				geometry={nodes.group1232702741.geometry}
				material={materials.mat23}
			/>
			<mesh
				geometry={nodes.group825219810.geometry}
				material={materials.mat23}
			/>
		</group>
	)
}

useGLTF.preload("/models/frame.glb")
