/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/switch.glb -o src/components/Switch.tsx -r public -t 
*/

import * as THREE from "three"
import { useGLTF } from "@react-three/drei"
import { type GLTF } from "three-stdlib"
import type { JSX } from "react"

type GLTFResult = GLTF & {
	nodes: {
		Cube004: THREE.Mesh
	}
	materials: {
		phong2SG: THREE.MeshStandardMaterial
	}
}

export default function Switch(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"/models/switch.glb"
	) as unknown as GLTFResult
	return (
		<group {...props} dispose={null} >
			<mesh
				geometry={nodes.Cube004.geometry}
				material={materials.phong2SG}
			/>
		</group>
	)
}

useGLTF.preload("/models/switch.glb")
