
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ceiling-fan.glb -o src/components/CeilingFan.tsx -r public -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Ceiling_Fan: THREE.Mesh
  }
  materials: {
    Mat: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export default function CeilingFan(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/ceiling-fan.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ceiling_Fan.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/models/ceiling-fan.glb')
