/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/desk.glb -o src/components/Desk.tsx -r public -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Desk_Drawer3_1: THREE.Mesh
    Desk_Drawer3_2: THREE.Mesh
    Desk_Drawer4_1: THREE.Mesh
    Desk_Drawer4_2: THREE.Mesh
    Desk_Drawer2_1: THREE.Mesh
    Desk_Drawer2_2: THREE.Mesh
    Desk_Drawer1_1: THREE.Mesh
    Desk_Drawer1_2: THREE.Mesh
    Desk_1: THREE.Mesh
    Desk_2: THREE.Mesh
  }
  materials: {
    DarkWood: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
  }
}

export default function Desk(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/desk.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.617, 0.781, -0.001]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Desk_Drawer3_1.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.Desk_Drawer3_2.geometry} material={materials.Wood} />
      </group>
      <group position={[-0.617, 0.617, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Desk_Drawer4_1.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.Desk_Drawer4_2.geometry} material={materials.Wood} />
      </group>
      <group position={[0.617, 0.617, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Desk_Drawer2_1.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.Desk_Drawer2_2.geometry} material={materials.Wood} />
      </group>
      <group position={[0.617, 0.781, -0.001]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Desk_Drawer1_1.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.Desk_Drawer1_2.geometry} material={materials.Wood} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Desk_1.geometry} material={materials.DarkWood} castShadow receiveShadow />
        <mesh geometry={nodes.Desk_2.geometry} material={materials.Wood} castShadow receiveShadow />
      </group>
    </group>
  )
}

useGLTF.preload('/models/desk.glb')
