/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import { useRef, type JSX } from "react"
import { useGLTF } from "@react-three/drei"
import type { GLTF } from "three/examples/jsm/Addons.js"

type GLTFResult = GLTF & {
	nodes: {
		Cube: THREE.Mesh
		Cube001: THREE.Mesh
		Cube002: THREE.Mesh
		Plane: THREE.Mesh
		Sphere: THREE.Mesh
	}
	materials: {
		wood: THREE.MeshStandardMaterial
		metal: THREE.MeshStandardMaterial
	}
}

export default function Door(props: JSX.IntrinsicElements["group"]) {
	const group = useRef<THREE.Group>(null)
	const { nodes } = useGLTF(
		"https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/door/model.gltf"
	) as unknown as GLTFResult
	return (
		<group ref={group} {...props} dispose={null}>
			<mesh
				geometry={nodes.Cube.geometry}
				material={nodes.Cube.material}
				position={[0, 1.34, 0]}
			>
				<mesh
					geometry={nodes.Cube001.geometry}
					material={nodes.Cube001.material}
					position={[-0.69, -0.08, 0.17]}
				>
					<mesh
						geometry={nodes.Cube002.geometry}
						material={nodes.Cube002.material}
						position={[0.53, -1.23, -0.17]}
					/>
					<mesh
						geometry={nodes.Plane.geometry}
						material={nodes.Plane.material}
						position={[1.27, 0, 0]}
					/>
					<mesh
						geometry={nodes.Sphere.geometry}
						material={nodes.Sphere.material}
						position={[1.31, 0, 0.05]}
					/>
				</mesh>
			</mesh>
		</group>
	)
}

useGLTF.preload(
	"https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/door/model.gltf"
)
