
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/light-bulb.glb -o src/components/LightBulb.tsx -r public -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    r000038478: THREE.Mesh
    r000134250: THREE.Mesh
    r000286730: THREE.Mesh
  }
  materials: {
    ['0.ReflectiveMaterial']: THREE.MeshStandardMaterial
    ['1.ReflectiveMaterial']: THREE.MeshStandardMaterial
    ['2.ReflectiveMaterial']: THREE.MeshStandardMaterial
  }
}

export default function LightBulb(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/light-bulb.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.r000038478.geometry} material={materials['0.ReflectiveMaterial']} />
      <mesh geometry={nodes.r000134250.geometry} material={materials['1.ReflectiveMaterial']} />
      <mesh geometry={nodes.r000286730.geometry} material={materials['2.ReflectiveMaterial']} />
    </group>
  )
}

useGLTF.preload('/models/light-bulb.glb')
