/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/single_bed.glb -o src/components/Singlebed.tsx -r public -t --transform 
Files: public/models/single_bed.glb [27.68KB] > D:\MyCode\React three fiber\my-room\src\components\single_bed-transformed.glb [5.04KB] (82%)
*/

import * as THREE from "three"
import { useGLTF } from "@react-three/drei"
import type { JSX } from "react"
import type { GLTF } from "three/examples/jsm/Addons.js"

type GLTFResult = GLTF & {
	nodes: {
		bedSingle_2: THREE.Mesh
		bedSingle_2_1: THREE.Mesh
		bedSingle_2_2: THREE.Mesh
		cover: THREE.Mesh
	}
	materials: {
		carpetWhite: THREE.MeshStandardMaterial
		wood: THREE.MeshStandardMaterial
		metal: THREE.MeshStandardMaterial
		carpet: THREE.MeshStandardMaterial
	}
}

const Singlebed = (props: JSX.IntrinsicElements["group"]) => {
	const { nodes, materials } = useGLTF(
		"/models/single_bed-transformed.glb"
	) as unknown as GLTFResult

	return (
		<group
			{...props}
			dispose={null}
			
		>
			<mesh geometry={nodes.cover.geometry} material={materials.carpet} />
			<mesh
				geometry={nodes.bedSingle_2.geometry}
				material={materials.carpetWhite}
			/>
			<mesh
				geometry={nodes.bedSingle_2_1.geometry}
				material={materials.wood}
			/>
			<mesh
				geometry={nodes.bedSingle_2_2.geometry}
				material={materials.metal}
			/>
		</group>
	)
}

useGLTF.preload("/models/single_bed-transformed.glb")
export default Singlebed
